import base64
import json
from abc import ABC, abstractmethod
from pathlib import Path

import aiofiles
import httpx
import structlog
from fastapi import HTTPException

from app.core.config import settings
from app.core.constants import AI_PROVIDER_TIMEOUT
from app.core.enums import AIProvider

logger = structlog.get_logger(__name__)


class AIMetadataResponse:
    """
    Нормализованный ответ AI-провайдера с метаданными изображения.
    """

    def __init__(self, title: str, description: str, keywords: list[str]):
        self.title = title
        self.description = description
        self.keywords = keywords


class BaseAIProvider(ABC):
    """
    Базовый интерфейс AI-провайдера для анализа изображений.
    """

    def __init__(self, model: str | None = None):
        self.model = model

    @abstractmethod
    async def generate_metadata(
        self,
        image_path: Path,
        shooting_context: str | None = None,
        file_number: int | None = None,
    ) -> AIMetadataResponse:
        """
        Генерирует метаданные для изображения.
        """


class MockImageMetadataProvider(BaseAIProvider):
    """
    Тестовый AI-провайдер для локальной разработки без внешних API-запросов.
    """

    async def generate_metadata(
        self,
        image_path: Path,
        shooting_context: str | None = None,
        file_number: int | None = None,
    ) -> AIMetadataResponse:
        """
        Возвращает тестовые метаданные для изображения.
        """
        logger.info(
            'mock_metadata_generation_started',
            file_number=file_number,
            image_path=str(image_path),
        )
        description = 'Test image description generated by mock provider.'

        if shooting_context:
            description = f'{description} Context: {shooting_context}'

        metadata = AIMetadataResponse(
            title=f'Test metadata for {image_path.name}',
            description=description,
            keywords=['test', 'image', 'metadata'],
        )

        logger.info(
            'mock_metadata_generation_completed',
            file_number=file_number,
            image_path=str(image_path),
            keywords_count=len(metadata.keywords),
        )

        return metadata


class OllamaImageMetadataProvider(BaseAIProvider):
    """
    AI-провайдер на базе Ollama
    для локальной генерации metadata по изображению.
    """

    async def generate_metadata(
        self,
        image_path: Path,
        shooting_context: str | None = None,
        file_number: int | None = None,
    ) -> AIMetadataResponse:
        """
        Отправляет изображение в локальную Ollama model и возвращает metadata.
        """
        logger.info(
            'ollama_metadata_generation_started',
            file_number=file_number,
            image_path=str(image_path),
            model=self.model,
        )

        image_base64 = await _encode_image_to_base64(image_path)

        prompt = (
            'Generate stock photo metadata for this image. '
            'Return only valid JSON '
            'with fields: title, description, keywords. '
            'keywords must be an array of strings.'
        )

        if shooting_context:
            prompt = f'{prompt} Use this shooting context: {shooting_context}'

        async with httpx.AsyncClient(timeout=AI_PROVIDER_TIMEOUT) as client:
            logger.info(
                'ollama_request_started',
                file_number=file_number,
                base_url=settings.OLLAMA_BASE_URL,
                model=self.model,
            )

            response = await client.post(
                f'{settings.OLLAMA_BASE_URL}/api/generate',
                json={
                    'model': self.model,
                    'prompt': prompt,
                    'images': [image_base64],
                    'stream': False,
                    'format': 'json',
                },
            )

        response.raise_for_status()
        logger.info(
            'ollama_response_received',
            file_number=file_number,
            status_code=response.status_code,
        )

        payload = response.json()
        raw_response = payload.get('response', '')
        logger.info(
            'ollama_raw_response_received',
            file_number=file_number,
            response_length=len(raw_response),
        )

        try:
            metadata = json.loads(raw_response)
        except json.JSONDecodeError as error:
            logger.exception(
                'ollama_response_json_parse_failed',
                file_number=file_number,
                raw_response=raw_response,
                error=str(error),
            )
            raise HTTPException(
                status_code=502,
                detail='Ollama provider returned invalid JSON',
            ) from error

        metadata_response = AIMetadataResponse(
            title=metadata.get('title') or '',
            description=metadata.get('description') or '',
            keywords=metadata.get('keywords') or [],
        )

        logger.info(
            'ollama_metadata_generation_completed',
            file_number=file_number,
            title=metadata_response.title,
            keywords_count=len(metadata_response.keywords),
        )

        return metadata_response


class GeminiImageMetadataProvider(BaseAIProvider):
    """
    AI-провайдер на базе Gemini для генерации metadata по изображению.
    """

    def __init__(self, model: str | None = None):
        super().__init__(model=model)
        if settings.GEMINI_API_KEY is None:
            raise HTTPException(
                status_code=500,
                detail='GEMINI_API_KEY is not configured',
            )

    async def generate_metadata(
        self,
        image_path: Path,
        shooting_context: str | None = None,
        file_number: int | None = None,
    ) -> AIMetadataResponse:
        """
        Генерирует метаданные через Gemini.
        """
        logger.info(
            'gemini_metadata_generation_started',
            file_number=file_number,
            image_path=str(image_path),
            model=self.model,
        )
        raise HTTPException(
            status_code=501,
            detail='Gemini provider is not implemented yet',
        )


class OpenRouterImageMetadataProvider(BaseAIProvider):
    """
    AI-провайдер на базе OpenRouter для генерации metadata по изображению.
    """

    def __init__(self, model: str | None = None):
        super().__init__(model=model)
        if settings.OPENROUTER_API_KEY is None:
            raise HTTPException(
                status_code=500,
                detail='OPENROUTER_API_KEY is not configured',
            )

    async def generate_metadata(
        self,
        image_path: Path,
        shooting_context: str | None = None,
        file_number: int | None = None,
    ) -> AIMetadataResponse:
        """
        Генерирует метаданные через OpenRouter.
        """
        logger.info(
            'openrouter_metadata_generation_started',
            file_number=file_number,
            image_path=str(image_path),
            model=self.model,
        )
        raise HTTPException(
            status_code=501,
            detail='OpenRouter provider is not implemented yet',
        )


def get_ai_provider(
    provider_name: str | AIProvider,
    model: str | None = None,
) -> BaseAIProvider:
    """Возвращает AI-провайдер по имени."""
    provider = AIProvider(provider_name)

    provider_classes: dict[AIProvider, type[BaseAIProvider]] = {
        AIProvider.MOCK: MockImageMetadataProvider,
        AIProvider.OLLAMA: OllamaImageMetadataProvider,
        AIProvider.GEMINI: GeminiImageMetadataProvider,
        AIProvider.OPENROUTER: OpenRouterImageMetadataProvider,
    }

    provider_class = provider_classes.get(provider)

    if provider_class is None:
        logger.error(
            'unsupported_ai_provider_configured',
            provider=provider,
        )

        raise HTTPException(
            status_code=500,
            detail=f'Unsupported AI provider: {provider}',
        )

    logger.info(
        'ai_provider_selected',
        provider=provider,
        model=model,
    )
    return provider_class(model=model)


async def _encode_image_to_base64(image_path: Path) -> str:
    """
    Кодирует изображение в base64 для отправки в AI-провайдер.
    """
    async with aiofiles.open(image_path, 'rb') as image_file:
        image_bytes = await image_file.read()

    return base64.b64encode(image_bytes).decode('utf-8')
