import base64
import json
from abc import ABC, abstractmethod
from pathlib import Path

import aiofiles
import httpx
import structlog
from fastapi import HTTPException

from app.core.config import settings
from app.core.enums import AIProvider, StockPlatform
from app.core.exceptions import AIProviderConfigurationError
from app.services.ai.constants import AI_PROVIDER_TIMEOUT
from app.services.desktop.ai_provider_api_keys import get_ai_provider_api_key
from app.services.prompt_templates.constants import (
    DEFAULT_PROMPT_LANGUAGE,
    METADATA_PROMPT_TEMPLATE_VERSION,
)
from app.services.prompt_templates.prompt_templates import (
    PromptTemplateRender,
    render_metadata_generation_prompt,
)

logger = structlog.get_logger(__name__)


class AIMetadataResponse:
    """
    Нормализованный ответ AI-провайдера с метаданными изображения.
    """

    def __init__(
        self,
        title: str,
        description: str,
        keywords: list[str],
        categories: list[str] | None = None,
        category_2: str | None = None,
        license_type: str | None = None,
        location_metadata: str | None = None,
        location_sublocation: str | None = None,
        location_city: str | None = None,
        location_province_state: str | None = None,
        location_country: str | None = None,
        editorial_date: str | None = None,
        is_editorial: bool = False,
        editorial_caption: str | None = None,
        has_people: bool | None = None,
        people_count: int | None = None,
        model_release_available: bool | None = None,
        releases: list[str] | None = None,
        ai_generated_content_disclosure: bool = False,
        is_illustration: bool | None = None,
        mature_content: bool | None = None,
        prompt_version: str | None = None,
        prompt_language: str = DEFAULT_PROMPT_LANGUAGE,
    ):
        self.title = title
        self.description = description
        self.keywords = keywords
        self.categories = categories or []
        self.category_2 = category_2
        self.license_type = license_type
        self.location_metadata = location_metadata
        self.location_sublocation = location_sublocation
        self.location_city = location_city
        self.location_province_state = location_province_state
        self.location_country = location_country
        self.editorial_date = editorial_date
        self.is_editorial = is_editorial
        self.editorial_caption = editorial_caption
        self.has_people = has_people
        self.people_count = people_count
        self.model_release_available = model_release_available
        self.releases = releases or []
        self.ai_generated_content_disclosure = ai_generated_content_disclosure
        self.is_illustration = is_illustration
        self.mature_content = mature_content
        self.prompt_version = prompt_version
        self.prompt_language = prompt_language


class BaseAIProvider(ABC):
    """
    Базовый интерфейс AI-провайдера для анализа изображений.
    """

    def __init__(self, model: str | None = None):
        self.model = model

    @abstractmethod
    async def generate_metadata(
        self,
        image_path: Path,
        shooting_context: str | None = None,
        file_number: int | None = None,
        stock_platform: StockPlatform | None = None,
    ) -> AIMetadataResponse:
        """
        Генерирует метаданные для изображения.
        """


class MockImageMetadataProvider(BaseAIProvider):
    """
    Тестовый AI-провайдер для локальной разработки без внешних API-запросов.
    """

    async def generate_metadata(
        self,
        image_path: Path,
        shooting_context: str | None = None,
        file_number: int | None = None,
        stock_platform: StockPlatform | None = None,
    ) -> AIMetadataResponse:
        """
        Возвращает тестовые метаданные для изображения.
        """
        logger.info(
            'mock_metadata_generation_started',
            file_number=file_number,
            image_path=str(image_path),
        )
        description = 'Test image description generated by mock provider.'

        if shooting_context:
            description = f'{description} Context: {shooting_context}'

        metadata = AIMetadataResponse(
            title=f'Test stock metadata for {image_path.name} image',
            description=description,
            keywords=[
                'test',
                'image',
                'metadata',
                'stock',
                'photo',
                'creative',
                'nature',
            ],
            categories=['Nature'],
            license_type='commercial',
            location_metadata='Unknown location',
            has_people=False,
            people_count=0,
            model_release_available=False,
            ai_generated_content_disclosure=False,
            prompt_version=METADATA_PROMPT_TEMPLATE_VERSION,
            prompt_language=DEFAULT_PROMPT_LANGUAGE,
        )

        logger.info(
            'mock_metadata_generation_completed',
            file_number=file_number,
            image_path=str(image_path),
            keywords_count=len(metadata.keywords),
        )

        return metadata


class OllamaImageMetadataProvider(BaseAIProvider):
    """
    AI-провайдер на базе Ollama
    для локальной генерации metadata по изображению.
    """

    async def generate_metadata(
        self,
        image_path: Path,
        shooting_context: str | None = None,
        file_number: int | None = None,
        stock_platform: StockPlatform | None = None,
    ) -> AIMetadataResponse:
        """
        Отправляет изображение в локальную Ollama model и возвращает metadata.
        """
        logger.info(
            'ollama_metadata_generation_started',
            file_number=file_number,
            image_path=str(image_path),
            model=self.model,
        )

        image_base64 = await _encode_image_to_base64(image_path)

        prompt_render = render_metadata_generation_prompt(
            shooting_context=shooting_context,
        )

        async with httpx.AsyncClient(timeout=AI_PROVIDER_TIMEOUT) as client:
            logger.info(
                'ollama_request_started',
                file_number=file_number,
                base_url=settings.OLLAMA_BASE_URL,
                model=self.model,
            )

            response = await client.post(
                f'{settings.OLLAMA_BASE_URL}/api/generate',
                json={
                    'model': self.model,
                    'prompt': prompt_render.prompt,
                    'images': [image_base64],
                    'stream': False,
                    'format': 'json',
                },
            )

        response.raise_for_status()
        logger.info(
            'ollama_response_received',
            file_number=file_number,
            status_code=response.status_code,
        )

        payload = response.json()
        raw_response = payload.get('response', '')
        logger.info(
            'ollama_raw_response_received',
            file_number=file_number,
            response_length=len(raw_response),
        )

        metadata_response = _build_metadata_response(
            metadata=_parse_provider_metadata_json(
                raw_response,
                provider_name='ollama',
                file_number=file_number,
            ),
            prompt_render=prompt_render,
        )

        logger.info(
            'ollama_metadata_generation_completed',
            file_number=file_number,
            title=metadata_response.title,
            keywords_count=len(metadata_response.keywords),
        )

        return metadata_response


class GeminiImageMetadataProvider(BaseAIProvider):
    """
    AI-провайдер на базе Gemini для генерации metadata по изображению.
    """

    def __init__(self, model: str | None = None):
        super().__init__(model=model)
        self.api_key = get_ai_provider_api_key(AIProvider.GEMINI)

        if self.api_key is None:
            raise AIProviderConfigurationError(
                reason_code='gemini_api_key_missing',
                message='GEMINI_API_KEY is not configured',
            )

    async def generate_metadata(
        self,
        image_path: Path,
        shooting_context: str | None = None,
        file_number: int | None = None,
        stock_platform: StockPlatform | None = None,
    ) -> AIMetadataResponse:
        """
        Генерирует метаданные через Gemini.
        """
        model = self.model or settings.GEMINI_MODEL
        logger.info(
            'gemini_metadata_generation_started',
            file_number=file_number,
            image_path=str(image_path),
            model=model,
        )

        image_base64 = await _encode_image_to_base64(image_path)
        prompt_render = render_metadata_generation_prompt(
            shooting_context=shooting_context,
        )

        async with httpx.AsyncClient(timeout=AI_PROVIDER_TIMEOUT) as client:
            logger.info(
                'gemini_request_started',
                file_number=file_number,
                base_url=settings.GEMINI_BASE_URL,
                model=model,
            )

            response = await client.post(
                f'{settings.GEMINI_BASE_URL}/models/{model}:generateContent',
                headers={'x-goog-api-key': self.api_key},
                json={
                    'contents': [
                        {
                            'parts': [
                                {'text': prompt_render.prompt},
                                {
                                    'inline_data': {
                                        'mime_type': 'image/jpeg',
                                        'data': image_base64,
                                    }
                                },
                            ]
                        }
                    ],
                    'generationConfig': {
                        'response_mime_type': 'application/json',
                    },
                },
            )

        response.raise_for_status()
        logger.info(
            'gemini_response_received',
            file_number=file_number,
            status_code=response.status_code,
        )

        payload = response.json()
        raw_response = _extract_gemini_text(payload)
        logger.info(
            'gemini_raw_response_received',
            file_number=file_number,
            response_length=len(raw_response),
        )

        metadata_response = _build_metadata_response(
            metadata=_parse_provider_metadata_json(
                raw_response,
                provider_name='gemini',
                file_number=file_number,
            ),
            prompt_render=prompt_render,
        )

        logger.info(
            'gemini_metadata_generation_completed',
            file_number=file_number,
            title=metadata_response.title,
            keywords_count=len(metadata_response.keywords),
        )

        return metadata_response


class OpenRouterImageMetadataProvider(BaseAIProvider):
    """
    AI-провайдер на базе OpenRouter для генерации metadata по изображению.
    """

    def __init__(self, model: str | None = None):
        super().__init__(model=model)
        self.api_key = get_ai_provider_api_key(AIProvider.OPENROUTER)

        if self.api_key is None:
            raise AIProviderConfigurationError(
                reason_code='openrouter_api_key_missing',
                message='OPENROUTER_API_KEY is not configured',
            )

    async def generate_metadata(
        self,
        image_path: Path,
        shooting_context: str | None = None,
        file_number: int | None = None,
        stock_platform: StockPlatform | None = None,
    ) -> AIMetadataResponse:
        """
        Генерирует метаданные через OpenRouter.
        """
        model = self.model or settings.OPENROUTER_MODEL
        logger.info(
            'openrouter_metadata_generation_started',
            file_number=file_number,
            image_path=str(image_path),
            model=model,
        )

        image_base64 = await _encode_image_to_base64(image_path)
        prompt_render = render_metadata_generation_prompt(
            shooting_context=shooting_context,
        )

        async with httpx.AsyncClient(timeout=AI_PROVIDER_TIMEOUT) as client:
            logger.info(
                'openrouter_request_started',
                file_number=file_number,
                base_url=settings.OPENROUTER_BASE_URL,
                model=model,
            )

            response = await client.post(
                f'{settings.OPENROUTER_BASE_URL}/chat/completions',
                headers={
                    'Authorization': f'Bearer {self.api_key}',
                    'Content-Type': 'application/json',
                },
                json={
                    'model': model,
                    'messages': [
                        {
                            'role': 'user',
                            'content': [
                                {
                                    'type': 'text',
                                    'text': prompt_render.prompt,
                                },
                                {
                                    'type': 'image_url',
                                    'image_url': {
                                        'url': (
                                            'data:image/jpeg;base64,'
                                            f'{image_base64}'
                                        ),
                                    },
                                },
                            ],
                        }
                    ],
                    'response_format': {'type': 'json_object'},
                },
            )

        response.raise_for_status()
        logger.info(
            'openrouter_response_received',
            file_number=file_number,
            status_code=response.status_code,
        )

        payload = response.json()
        raw_response = _extract_openrouter_text(payload)
        logger.info(
            'openrouter_raw_response_received',
            file_number=file_number,
            response_length=len(raw_response),
        )

        metadata_response = _build_metadata_response(
            metadata=_parse_provider_metadata_json(
                raw_response,
                provider_name='openrouter',
                file_number=file_number,
            ),
            prompt_render=prompt_render,
        )

        logger.info(
            'openrouter_metadata_generation_completed',
            file_number=file_number,
            title=metadata_response.title,
            keywords_count=len(metadata_response.keywords),
        )

        return metadata_response


def get_ai_provider(
    provider_name: str | AIProvider,
    model: str | None = None,
) -> BaseAIProvider:
    """Возвращает AI-провайдер по имени."""
    provider = AIProvider(provider_name)

    provider_classes: dict[AIProvider, type[BaseAIProvider]] = {
        AIProvider.MOCK: MockImageMetadataProvider,
        AIProvider.OLLAMA: OllamaImageMetadataProvider,
        AIProvider.GEMINI: GeminiImageMetadataProvider,
        AIProvider.OPENROUTER: OpenRouterImageMetadataProvider,
    }

    provider_class = provider_classes.get(provider)

    if provider_class is None:
        logger.error(
            'unsupported_ai_provider_configured',
            provider=provider,
        )

        raise AIProviderConfigurationError(
            reason_code='unsupported_ai_provider',
            message=f'Unsupported AI provider: {provider}',
        )

    logger.info(
        'ai_provider_selected',
        provider=provider,
        model=model,
    )
    return provider_class(model=model)


async def _encode_image_to_base64(image_path: Path) -> str:
    """
    Кодирует изображение в base64 для отправки в AI-провайдер.
    """
    async with aiofiles.open(image_path, 'rb') as image_file:
        image_bytes = await image_file.read()

    return base64.b64encode(image_bytes).decode('utf-8')


def _parse_provider_metadata_json(
    raw_response: str,
    *,
    provider_name: str,
    file_number: int | None,
) -> dict:
    try:
        metadata = json.loads(raw_response)
    except json.JSONDecodeError as error:
        logger.exception(
            f'{provider_name}_response_json_parse_failed',
            file_number=file_number,
            raw_response=raw_response,
            error=str(error),
        )
        raise HTTPException(
            status_code=502,
            detail=f'{provider_name.title()} provider returned invalid JSON',
        ) from error

    if not isinstance(metadata, dict):
        logger.warning(
            f'{provider_name}_response_json_shape_invalid',
            file_number=file_number,
            raw_response=raw_response,
        )
        raise HTTPException(
            status_code=502,
            detail=(
                f'{provider_name.title()} provider returned non-object JSON'
            ),
        )

    return metadata


def _extract_location_components(
    metadata: dict,
) -> tuple[str | None, str | None, str | None, str | None]:
    """
    Достаёт структурированные компоненты локации из ответа AI.

    Поддерживает вложенный объект ``location`` со стандартными IPTC-полями.
    """
    location = metadata.get('location')

    if not isinstance(location, dict):
        return (None, None, None, None)

    def _component(*keys: str) -> str | None:
        for key in keys:
            value = _extract_optional_string(location.get(key))

            if value is not None:
                return value

        return None

    return (
        _component('sublocation', 'sub_location'),
        _component('city'),
        _component('province_state', 'province', 'state'),
        _component('country', 'country_name'),
    )


def _compose_location_string(
    *components: str | None,
) -> str | None:
    """
    Собирает человекочитаемую строку локации из известных компонентов.
    """
    parts = [component for component in components if component]

    if not parts:
        return None

    return ', '.join(parts)


def _build_metadata_response(
    *,
    metadata: dict,
    prompt_render: PromptTemplateRender,
) -> AIMetadataResponse:
    (
        location_sublocation,
        location_city,
        location_province_state,
        location_country,
    ) = _extract_location_components(metadata)
    location_metadata = _extract_optional_string(
        metadata.get('location_metadata')
    ) or _compose_location_string(
        location_sublocation,
        location_city,
        location_province_state,
        location_country,
    )

    return AIMetadataResponse(
        title=metadata.get('title') or '',
        description=metadata.get('description') or '',
        keywords=_extract_string_list(metadata.get('keywords')),
        categories=_extract_string_list(metadata.get('categories')),
        category_2=_extract_optional_string(metadata.get('category_2')),
        license_type=_extract_optional_string(metadata.get('license_type')),
        location_metadata=location_metadata,
        location_sublocation=location_sublocation,
        location_city=location_city,
        location_province_state=location_province_state,
        location_country=location_country,
        editorial_date=_extract_optional_string(
            metadata.get('editorial_date')
        ),
        is_editorial=bool(metadata.get('is_editorial') or False),
        editorial_caption=_extract_optional_string(
            metadata.get('editorial_caption')
        ),
        has_people=_extract_optional_bool(metadata.get('has_people')),
        people_count=_extract_optional_int(metadata.get('people_count')),
        model_release_available=_extract_optional_bool(
            metadata.get('model_release_available')
        ),
        releases=_extract_string_list(metadata.get('releases')),
        ai_generated_content_disclosure=bool(
            metadata.get('ai_generated_content_disclosure') or False
        ),
        is_illustration=_extract_optional_bool(
            metadata.get('is_illustration')
        ),
        mature_content=_extract_optional_bool(metadata.get('mature_content')),
        prompt_version=prompt_render.version,
        prompt_language=prompt_render.language,
    )


def _extract_gemini_text(payload: object) -> str:
    if not isinstance(payload, dict):
        return ''

    candidates = payload.get('candidates')
    if not isinstance(candidates, list) or not candidates:
        return ''

    candidate = candidates[0]
    if not isinstance(candidate, dict):
        return ''

    content = candidate.get('content')
    if not isinstance(content, dict):
        return ''

    return _extract_text_from_content_parts(content.get('parts'))


def _extract_openrouter_text(payload: object) -> str:
    if not isinstance(payload, dict):
        return ''

    choices = payload.get('choices')
    if not isinstance(choices, list) or not choices:
        return ''

    choice = choices[0]
    if not isinstance(choice, dict):
        return ''

    message = choice.get('message')
    if not isinstance(message, dict):
        return ''

    content = message.get('content')
    if isinstance(content, str):
        return content

    return _extract_text_from_content_parts(content)


def _extract_text_from_content_parts(parts: object) -> str:
    if not isinstance(parts, list):
        return ''

    text_parts: list[str] = []
    for part in parts:
        if not isinstance(part, dict):
            continue

        text = part.get('text')
        if isinstance(text, str):
            text_parts.append(text)

    return ''.join(text_parts)


def _extract_string_list(value: object) -> list[str]:
    if not isinstance(value, list):
        return []

    return [str(item) for item in value if str(item).strip()]


def _extract_optional_string(value: object) -> str | None:
    if value is None:
        return None

    normalized = str(value).strip()
    return normalized or None


def _extract_optional_bool(value: object) -> bool | None:
    if value is None:
        return None

    if isinstance(value, bool):
        return value

    normalized = str(value).strip().lower()

    if normalized in {'true', '1', 'yes'}:
        return True
    if normalized in {'false', '0', 'no'}:
        return False

    return None


def _extract_optional_int(value: object) -> int | None:
    if value is None:
        return None

    if isinstance(value, bool):
        return None

    if isinstance(value, int):
        return value if value >= 0 else None

    normalized = str(value).strip()

    if not normalized:
        return None

    try:
        parsed = int(normalized)
    except ValueError:
        return None

    return parsed if parsed >= 0 else None
